# Generated by Django 5.2.12 on 2026-04-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_taskchangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='overdue_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
